// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM88QfP0zMLq7dHWDzTNi_EcxGPuirkjA',
    appId: '1:268843058729:android:d7caf1fc4389947fdb3e38',
    messagingSenderId: '268843058729',
    projectId: 'photoblog-ea334',
    databaseURL: 'https://photoblog-ea334.firebaseio.com',
    storageBucket: 'photoblog-ea334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN65PvzC9UTh90IF1-4896eN7O4tiF27U',
    appId: '1:268843058729:ios:ad78978808dbe466db3e38',
    messagingSenderId: '268843058729',
    projectId: 'photoblog-ea334',
    databaseURL: 'https://photoblog-ea334.firebaseio.com',
    storageBucket: 'photoblog-ea334.appspot.com',
    iosClientId: '268843058729-crsl01fpabgokl4kd9mdluiabuo8v74n.apps.googleusercontent.com',
    iosBundleId: 'com.anasmisbah.qrCode',
  );
}
